name: Build

on: [push]

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the app
      run: swift build -c release

    - name: Run tests
      run: swift test
    
    - name: Archive binary
      uses: actions/upload-artifact@v1
      with:
        name: Postman
        path: .build/release/Postman
