name: Build

on: [push]

jobs:
  build-mac:
    # https://github.com/actions/runner-images/tree/main/images/macos
    runs-on: macos-15
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.app/Contents/Developer

    steps:
      - uses: actions/checkout@v4

      - name: Build the app
        run: |
          swift build -c release
          mv $(swift build -c release --show-bin-path)/Postman .

      - name: Run tests
        run: swift test

      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: postman-mac
          path: Postman

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the app
        run: |
          swift build -c release
          mv $(swift build -c release --show-bin-path)/Postman .

      - name: Run tests
        run: swift test

      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: postman-linux
          path: Postman
